parameters:
    app.kitchen.message_class_prefix: 'App\Kitchen\Application\Message'

services:
    app.kitchen.message.serializer:
        class: 'Mmalessa\MessengerAddons\DefaultMessageSerializer'
        arguments:
            $messageClassPrefix: '%app.kitchen.message_class_prefix%'

    app.kitchen.messagebus.serializer:
        class: 'Mmalessa\MessengerAddons\AmqpMessageSerializer'
        arguments:
            $targetBusName: 'kitchen.message.bus'
            $messageSerializer: '@app.kitchen.message.serializer'

    app.kitchen.messagebus.middleware.add_stamp:
        class: 'Mmalessa\MessengerAddons\AddAmqpStampMiddleware'
        arguments:
            $messageClassPrefix: '%app.kitchen.message_class_prefix%'

framework:
    messenger:
        transports:
            kitchen_transport:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: 'app.kitchen.messagebus.serializer'
                options:
                    exchange:
                        name: pizza_house_messages
                        type: topic
                    queues:
                        messages_for_kitchen:
                            binding_keys:
                                - 'Kitchen.Command.*'
                retry_strategy:
                    max_retries: 2
                    delay: 2000
                    multiplier: 4
        routing:
            'App\Kitchen\Application\Message\KitchenMessageInterface': kitchen_transport
        buses:
            kitchen.message.bus:
                middleware:
                    - 'app.kitchen.messagebus.middleware.add_stamp'