services:
    App\Kitchen\Application\MessageHandler\:
        resource: '%kernel.project_dir%/src/Kitchen/Application/MessageHandler/*Handler.php'
        tags:
            - { name: messenger.message_handler, from_transport: kitchen_transport}
        bind:
            $messageBus: '@kitchen.message.bus'
            $logger: '@monolog.logger.kitchen'
            $delay: '@app.kitchen.some_delay'


    app.kitchen.some_delay:
        class: Mmalessa\SomeTools\SomeDelay
        arguments:
            $delayTime: 1
            $logger: '@monolog.logger.kitchen'
