services:
    App\Waiter\Application\MessageHandler\:
        resource: '%kernel.project_dir%/src/Waiter/Application/MessageHandler/*Handler.php'
        tags:
            - { name: messenger.message_handler }
        bind:
            $messageBus: '@waiter.message.bus'
