services:
    App\Waiter\Application\MessageHandler\:
        resource: '%kernel.project_dir%/src/Waiter/Application/MessageHandler/*Handler.php'
        tags:
            - { name: messenger.message_handler, from_transport: waiter_transport }
        bind:
            $messageBus: '@waiter.message.bus'
            $logger: '@monolog.logger.waiter'
            $communicator: '@App\Waiter\Domain\CommunicatorInterface'
