parameters:
    app.waiter.message_class_prefix: 'App\Waiter\Application\Message'

services:
    app.waiter.message.serializer:
        class: 'Mmalessa\MessengerAddons\DefaultMessageSerializer'
        arguments:
            $messageClassPrefix: '%app.waiter.message_class_prefix%'

    app.waiter.messagebus.serializer:
        class: 'Mmalessa\MessengerAddons\AmqpMessageSerializer'
        arguments:
            $targetBusName: 'waiter.message.bus'
            $messageSerializer: '@app.waiter.message.serializer'

    app.waiter.messagebus.middleware.add_stamp:
        class: 'Mmalessa\MessengerAddons\AddAmqpStampMiddleware'
        arguments:
            $messageClassPrefix: '%app.waiter.message_class_prefix%'

framework:
    messenger:
        transports:
            waiter_transport:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: 'app.waiter.messagebus.serializer'
                options:
                    exchange:
                        name: pizza_house_messages
                        type: topic
                    queues:
                        messages_for_waiter:
                            binding_keys:
                                - 'Waiter.Command.*'
                retry_strategy:
                    max_retries: 2
                    delay: 2000
                    multiplier: 4
        routing:
            'App\Waiter\Application\Message\WaiterMessageInterface': waiter_transport
        buses:
            waiter.message.bus:
                middleware:
                    - 'app.waiter.messagebus.middleware.add_stamp'