services:
    App\ProcessManager\UI\ConsoleCommand\:
        resource: '%kernel.project_dir%/src/ProcessManager/UI/ConsoleCommand/**/*Command.php'
        tags:
            - { name: console.command }
        bind:
            $messageBus: '@process_manager.message.bus'
            $simpleServingRepository: '@app.simple-serving.repository'
