parameters:
    app.process_manager.message_class_prefix: 'App\ProcessManager\Application\Message'

services:
    app.process_manager.message.serializer:
        class: 'Mmalessa\MessengerAddons\DefaultMessageSerializer'
        arguments:
            $messageClassPrefix: '%app.process_manager.message_class_prefix%'

    app.process_manager.messagebus.serializer:
        class: 'Mmalessa\MessengerAddons\AmqpMessageSerializer'
        arguments:
            $targetBusName: 'process_manager.message.bus'
            $messageSerializer: '@app.process_manager.message.serializer'

    app.process_manager.messagebus.middleware.add_stamp:
        class: 'Mmalessa\MessengerAddons\AddAmqpStampMiddleware'
        arguments:
            $messageClassPrefix: '%app.process_manager.message_class_prefix%'

framework:
    messenger:
        transports:
            process_manager_transport:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: 'app.process_manager.messagebus.serializer'
                options:
                    exchange:
                        name: pizza_house_messages
                        type: topic
                    queues:
                        messages_for_process_manager:
                            binding_keys:
                                - 'ProcessManager.Command.*'
                                - '*.Event.*'
                retry_strategy:
                    max_retries: 1
                    delay: 1000
                    multiplier: 1
        routing:
            'App\ProcessManager\Application\Message\ProcessManagerMessageInterface': process_manager_transport
        buses:
            process_manager.message.bus:
                middleware:
                    - 'app.process_manager.messagebus.middleware.add_stamp'
