services:

    App\ProcessManager\Application\Process\:
        resource: '%kernel.project_dir%/src/ProcessManager/Application/Process/*Process.php'
        autoconfigure: true
        bind:
            $messageBus: '@process_manager.message.bus'
            $logger: '@monolog.logger.process_manager'
            $servingCustomersRepository: '@App\ProcessManager\Domain\ServingCustomers\ServingCustomersRepositoryInterface'
