services:

    App\ProcessManager\Domain\ServingCustomers\ServingCustomersRepositoryInterface:
        alias: App\ProcessManager\Infrastructure\ServingCustomers\Repository\Redis\ServingCustomersRepository

    App\ProcessManager\Infrastructure\ServingCustomers\Repository\InMemory\ServingCustomersRepository:

    app.repository.redis:
        class: Predis\Client
        arguments:
            $parameters: '%env(REDIS_URL)%'

    App\ProcessManager\Infrastructure\ServingCustomers\Repository\Redis\ServingCustomersRepository:
        arguments:
            $client: '@app.repository.redis'
            $ttl: 3600


    App\ProcessManager\Infrastructure\Common\Repository\File\MessageRepository:
        arguments:
            $storageDirectory: '/app/storage/'

    app.simple-serving.repository:
        class: EventSauce\EventSourcing\EventSourcedAggregateRootRepository
        arguments:
            $aggregateRootClassName: App\ProcessManager\Domain\SimpleServing\SimpleServing
            $messageRepository: '@App\ProcessManager\Infrastructure\Common\Repository\File\MessageRepository'

