services:

    App\ProcessManager\Domain\ServingCustomers\ServingCustomersRepositoryInterface:
        alias: App\ProcessManager\Infrastructure\ServingCustomers\Repository\Redis\ServingCustomersRepository

    App\ProcessManager\Infrastructure\ServingCustomers\Repository\InMemory\ServingCustomersRepository:

    app.repository.redis:
        class: Predis\Client
        arguments:
            $parameters: '%env(REDIS_URL)%'

    App\ProcessManager\Infrastructure\ServingCustomers\Repository\Redis\ServingCustomersRepository:
        arguments:
            $client: '@app.repository.redis'
            $ttl: 3600
