services:
    App\HeavyWorker\Application\MessageHandler\:
        resource: '%kernel.project_dir%/src/HeavyWorker/Application/MessageHandler/*Handler.php'
        tags:
            - { name: messenger.message_handler, from_transport: heavy_worker_transport}
        bind:
            $logger: '@monolog.logger.heavy_worker'
            $delay: '@app.heavy_worker.some_delay'

    app.heavy_worker.some_delay:
        class: Mmalessa\SomeTools\SomeDelay
        arguments:
            $delayTime: 1
            $logger: '@monolog.logger.heavy_worker'
