parameters:
    app.heavy_worker.message_class_prefix: 'App\HeavyWorker\Application\Message'

services:
    app.heavy_worker.message.serializer:
        class: 'Mmalessa\MessengerAddons\DefaultMessageSerializer'
        arguments:
            $messageClassPrefix: '%app.heavy_worker.message_class_prefix%'

    app.heavy_worker.messagebus.serializer:
        class: 'Mmalessa\MessengerAddons\AmqpMessageSerializer'
        arguments:
            $targetBusName: 'heavy_worker.message.bus'
            $messageSerializer: '@app.heavy_worker.message.serializer'

    app.heavy_worker.messagebus.middleware.add_stamp:
        class: 'Mmalessa\MessengerAddons\AddAmqpStampMiddleware'
        arguments:
            $messageClassPrefix: '%app.heavy_worker.message_class_prefix%'

framework:
    messenger:
        transports:
            heavy_worker_transport:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: 'app.heavy_worker.messagebus.serializer'
                options:
                    exchange:
                        name: pizza_house_messages
                        type: topic
                    queues:
                        messages_for_heavy_worker:
                            binding_keys:
                                - 'HeavyWorker.Command.*'
                retry_strategy:
                    max_retries: 2
                    delay: 2000
                    multiplier: 4
        routing:
            'App\HeavyWorker\Application\Message\HeavyWorkerMessageInterface': heavy_worker_transport
        buses:
            heavy_worker.message.bus:
                middleware:
                    - 'app.heavy_worker.messagebus.middleware.add_stamp'