services:

    App\OrderManager\Application\MessageHandler\TableService\:
        resource: '%kernel.project_dir%/src/OrderManager/Application/MessageHandler/TableService/*Handler.php'
        tags:
            - { name: messenger.message_handler, from_transport: order_manager_transport }
        bind:
            $messageBus: '@order_manager.message.bus'
            $logger: '@monolog.logger.order_manager'
            $tableServiceRepository: '@App\OrderManager\Domain\TableServiceRepositoryInterface'