services:

    App\OrderManager\Domain\TableServiceRepositoryInterface:
#        alias: App\OrderManager\Infrastructure\Repository\InMemory\TableServiceRepository
        alias: App\OrderManager\Infrastructure\Repository\Redis\TableServiceRepository

    App\OrderManager\Infrastructure\Repository\InMemory\TableServiceRepository:

    app.repository.redis:
        class: Predis\Client
        arguments:
            $parameters: '%env(REDIS_URL)%'
    App\OrderManager\Infrastructure\Repository\Redis\TableServiceRepository:
        arguments:
            $client: '@app.repository.redis'
            $ttl: 3600