services:

    App\OrderManager\Domain\TableServiceRepositoryInterface:
        alias: App\OrderManager\Infrastructure\Repository\InMemory\TableServiceRepository

    App\OrderManager\Infrastructure\Repository\InMemory\TableServiceRepository: