version: '3.1'

services:

  app:
    image: ${APP_IMAGE}
    container_name: ${CONTAINER_NAME}
    restart: on-failure
    volumes:
      - ../:/app/
    working_dir: /app
    # ports:
    #   - 80:80
    #   - 443:443
    # command: [tail, '-f', /dev/null]
    tty: true
