version: '3.7'

services:

    app:
        build:
            context: php
            target: ${BUILD_TARGET}
            args:
                DEVELOPER_UID: ${DEVELOPER_UID}
        user: ${DEVELOPER_UID}:${DEVELOPER_UID}
        container_name: ${COMPOSE_PROJECT_NAME}-app
        depends_on:
            rabbitmq:
                condition: service_healthy
            redis:
                condition: service_started
        restart: on-failure
        volumes:
            - ../:/app/
            - ./php/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
            - ./php/php_dev.ini:/usr/local/etc/php/conf.d/99-overrides_dev.ini
            - app_home:/home/developer
#            - ../../.ssh:/home/developer/.ssh
        working_dir: /app
        tty: true
        networks:
            devapp:
        extra_hosts:
            - host.docker.internal:host-gateway

    rabbitmq:
        image: rabbitmq:3.11.9-management
        container_name: ${COMPOSE_PROJECT_NAME}-rabbitmq
        restart: on-failure
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            devapp:
        volumes:
            - rabbitmq_mnesia:/var/lib/rabbitmq/mnesia
        healthcheck:
            test: rabbitmq-diagnostics check_port_connectivity
            start_period: 60s
            interval: 30s
            timeout: 10s
            retries: 3
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

    redis:
        image: redis:7.0.5
        container_name: ${COMPOSE_PROJECT_NAME}-redis
        restart: on-failure
        volumes:
            - redis_data:/data
        networks:
            devapp:
        ports:
            - "6379:6379"

    redis-commander:
        image: rediscommander/redis-commander:latest
        container_name: ${COMPOSE_PROJECT_NAME}-redis-commander
        restart: on-failure
        environment:
            REDIS_HOSTS: local:dev-redis:6379
        networks:
            devapp:
        ports:
            - "8081:8081"

networks:
    devapp:
        name: devapp

volumes:
    redis_data:
    rabbitmq_mnesia:
    app_home:
