parameters:
    app.menu.message_class_prefix: 'App\Menu\Application\Message'

services:
    app.menu.message.serializer:
        class: 'Mmalessa\MessengerAddons\DefaultMessageSerializer'
        arguments:
            $messageClassPrefix: '%app.menu.message_class_prefix%'

    app.menu.messagebus.serializer:
        class: 'Mmalessa\MessengerAddons\AmqpMessageSerializer'
        arguments:
            $targetBusName: 'menu.message.bus'
            $messageSerializer: '@app.menu.message.serializer'

    app.menu.messagebus.middleware.add_stamp:
        class: 'Mmalessa\MessengerAddons\AddAmqpStampMiddleware'
        arguments:
            $messageClassPrefix: '%app.menu.message_class_prefix%'

framework:
    messenger:
        transports:
            menu_transport:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: 'app.menu.messagebus.serializer'
                options:
                    exchange:
                        name: pizza_house_messages
                        type: topic
                    queues:
                        messages_for_menu:
                            binding_keys:
                                - 'Menu.Command.*'
                retry_strategy:
                    max_retries: 2
                    delay: 2000
                    multiplier: 4
        routing:
            'App\Menu\Application\Message\MenuMessageInterface': menu_transport
        buses:
            menu.message.bus:
                middleware:
                    - 'app.menu.messagebus.middleware.add_stamp'