parameters:
    menu_yaml_file: "%kernel.project_dir%/yaml_storage/menu.yaml"
services:

    App\Menu\Domain\Query\GetMenuQueryInterface:
        alias: App\Menu\Infrastructure\Query\Yaml\GetMenuQuery

    App\Menu\Infrastructure\Query\Yaml\:
        resource: '%kernel.project_dir%/src/Menu/Infrastructure/Query/Yaml/*.php'
        bind:
            $menuYamlFile: '%menu_yaml_file%'
